---
- hosts: localhost
  become: yes

  tasks:
    - name: Retrieve helm binary archive.
      unarchive:
        src: https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz
        dest: /tmp
        creates: /usr/bin/helm
        remote_src: yes
       
    - name: Move helm binary into place.
      command: cp /tmp/linux-amd64/helm /usr/bin/helm
      args:
        creates: /usr/bin/helm
        
    - name: Add stable promotheus chart repo
      community.kubernetes.helm_repository:
        name: promotheus-stable-repo
        repo_url: "https://prometheus-community.github.io/helm-charts"
    
    - name: Add stable grafana chart repo
      community.kubernetes.helm_repository:
        name: grafana-stable-repo
        repo_url: https://grafana.github.io/helm-charts         

    - name: Deploy latest version of Prometheus chart inside monitoring namespace (and create it).
      community.kubernetes.helm:
        name: prometheus
        chart_ref: promotheus-stable-repo/prometheus
        release_namespace: prometheus
        create_namespace: true
        kubeconfig: /var/lib/jenkins/.kube/config
        values:
          persistence:
            storageClassName: "gp2"

    - name: Deploy latest version of Grafana chart inside monitoring namespace with values
      community.kubernetes.helm:
        name: grafana-test
        chart_ref: grafana-stable-repo/grafana
        release_namespace: monitoring
        kubeconfig: /var/lib/jenkins/.kube/config
        values:
          replicas: 2
          adminPassword: 'welcome'
          persistence:
            storageClassName: "gp2"
            enabled: true
          service:
            type: "LoadBalancer"
        values_files:
          - grafana.yaml
